---
deployment:
  tasks:
    - export DEPLOYPATH=/home/harpiaconsultt-arch/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH (se houver uma pasta de imagens/estilos)
